Refactor recovery workflow for better handling
Updated recovery workflow to improve URL handling and script execution.

diff --git a/.github/workflows/recovery.yml b/.github/workflows/recovery.yml
--- a/.github/workflows/recovery.yml
+++ b/.github/workflows/recovery.yml
@@ -4,12 +4,8 @@ on:
   workflow_dispatch:
     inputs:
       RECOVERY_URL:
-        description: 'RECOVERY URL'
+        description: 'DIRECT Link to recovery.img (use catbox.moe)'
         required: true
-        default: 'https://transfer.sh/(RECOMMENDED)'
-
-env:
-  RECOVERY_URL: https://oshi.at/Rpjg
 
 jobs:
   build:
@@ -17,32 +13,37 @@ jobs:
 
     steps:
     - name: Check Out
-      uses: actions/checkout@main
+      uses: actions/checkout@v4
 
     - name: Prepare the environment
       run: |
+        sudo apt update
         sudo apt install git wget lz4 tar openssl python3 -y
 
     - name: Fetch image from URL
       run: |
-        ls
-        pwd
-        wget ${{github.event.inputs.RECOVERY_URL }} -O recovery.img
+        wget "${{ github.event.inputs.RECOVERY_URL }}" -O recovery.img
+        # Check if the file is too small (meaning it's a webpage, not an image)
+        if [ $(stat -c%s "recovery.img") -lt 1000000 ]; then
+          echo "ERROR: The link provided is not a direct download link!"
+          exit 1
+        fi
 
-    - name: Patch Process-1
+    - name: Patch Process
       run: |
-        chmod a+x script1.sh
-        chmod a+x magiskboot
+        chmod a+x script1.sh script2.sh magiskboot
+        # Fix the hardcoded paths in the scripts on the fly
+        sed -i "s|/home/runner/work/Patch-Recovery/Patch-Recovery/|$GITHUB_WORKSPACE/|g" script2.sh
+        
         ./script1.sh || true
-
-    - name: Patch Process-2
-      run: |
-        chmod a+x script2.sh
         ./script2.sh || true
+        
         python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
-        python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery.img |cut -f 1 -d ' ') --image recovery-patched.img --key phh.pem --algorithm SHA256_RSA4096
-        mkdir output && cd output
-        mv ../recovery-patched.img recovery.img
+        python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery.img | cut -f 1 -d ' ') --image recovery-patched.img --key phh.pem --algorithm SHA256_RSA4096
+        
+        mkdir output
+        mv recovery-patched.img output/recovery.img
+        cd output
         tar cvf fastbootd-recovery.tar recovery.img
         md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar
         mv fastbootd-recovery.tar fastbootd-recovery.tar.md5
@@ -50,5 +51,5 @@ jobs:
     - name: Upload Recovery
       uses: actions/upload-artifact@v4
       with:
-        path: /home/runner/work/Patch-Recovery/Patch-Recovery/output/*.md5
         name: Patched-Recovery
+        path: output/fastbootd-recovery.tar.md5
